updated format

diff --git a/.github/workflows/Project-Multistages.yaml b/.github/workflows/Project-Multistages.yaml
--- a/.github/workflows/Project-Multistages.yaml
+++ b/.github/workflows/Project-Multistages.yaml
@@ -1,32 +1,39 @@
----
-name: Build Multistages
+name: Docker Build & Test
+
 on:
   push:
-    branches:
-      - main
+    branches: [ "main" ]
   pull_request:
-    branches:
-      - main
+
 jobs:
   docker:
-      runs-on: ubuntu:latest
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v3
-        - name: Setup Docker Buildx
-          uses: docker/setup-buildx-action@v2
-        - name: Build Docker image
-          run: |
-            docker build -t --name test-app flask-multistage .
-        - name: Run Container
-          run: |
-            docker run -d -p 5000:5000 flaks-multistage
-            sleep 5
-            docker ps -a
-        - name: Test app with curl
-          run: |
-            curl -f http://localhost:5000 || (docker logs test-app && exit 1)
-        - name: Stop container and remove
-          run: |
-            docker stop test-app && docker rm test-app
-            docker rmi flask-multistage
+    runs-on: ubuntu-latest
+    steps:
+      # Step 1 - Checkout code
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      # Step 2 - Set up Docker Buildx
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      # Step 3 - Build Docker image
+      - name: Build Docker image
+        run: docker build -t flask-multistage .
+
+      # Step 4 - Run container
+      - name: Run container
+        run: |
+          docker run -d -p 5000:5000 --name testapp flask-multistage
+          sleep 5
+          docker ps -a
+
+      # Step 5 - Test the endpoint
+      - name: Test app with curl
+        run: curl -f http://localhost:5000 || (docker logs testapp && exit 1)
+
+      # Step 6 - Cleanup
+      - name: Stop and remove container
+        run: |
+          docker stop testapp
+          docker rm testapp
